### ISSUE TITLE
Sign up doesn't work as intended

### ISSUE THREAD

**Issue by z0l0git** [z0l0git/income-expense#3]
Added an if statement to check if email contains @ letter but the front-end pushes to the success page when the email is invalid.

**Comment by Sky-De** [comment]
@z0l0git hi 

************************************************************************************************************
**FIRST SOLUTION**

add this to your code 
const regex = /^((?!\.)[\w\-_.]*[^.])(@\w+)(\.\w+(\.\w+)?[^.\W])$/

then with the if statement to check

if( !regex.test(userData.email) ) {
your message to show email is not valid
}

************************************************************************************************************

**Another solution** 

Wrap all your inputs in form tag
add onSubmit to form
add submit btn to form
then it will automatically check for email validation

**Comment by z0l0git** [comment]
> @z0l0git hi 
> 
> 
> 
> ************************************************************************************************************
> 
> **FIRST SOLUTION**
> 
> 
> 
> add this to your code 
> 
> const regex = /^((?!\.)[\w\-_.]*[^.])(@\w+)(\.\w+(\.\w+)?[^.\W])$/
> 
> 
> 
> then with the if statement to check
> 
> 
> 
> if( !regex.test(userData.email) ) {
> 
> your message to show email is not valid
> 
> }
> 
> 
> 
> ************************************************************************************************************
> 
> 
> 
> **Another solution** 
> 
> 
> 
> Wrap all your inputs in form tag
> 
> add onSubmit to form
> 
> add submit btn to form
> 
> then it will automatically check for email validation
> 
> 

Thank You, I was checking everything at the back end of my program, did't think to check them the front-end for some reason.
